// Intro Animation
// ###############
//
// Builds the opening camera animation keyframe sequence. Called once on first
// visit; the sequence is passed to CameraAnimator.play().

import S from "./settings.js"
import { PATH } from "./camera-animator.js"

export function buildIntro(sunPosition) {
  const constVal = x => ({ from: x, to: x })
  const { x, y, z } = sunPosition
  const [tx, ty, tz] = [0, 0.6, 10.0]
  return [
    { // inside r
      type: PATH.LINEAR_QUAT,
      duration: 3,
      from: [-12.76, 2.03, 5.86, -0.43 * Math.PI, 0.0 * Math.PI, 0.0 * Math.PI],
      to: [-12.76, 2.03, 5.86, -0.43 * Math.PI, 0.0 * Math.PI, 0.0 * Math.PI],
      fixedHeight: true,
      fadeIn: true,
      fadeOut: true,
      timeOverrides: {
        timeOfDay: constVal(17.5),
        rain: constVal(0.0),
        cloudBase: constVal(70),
        cloudTop: constVal(130),
        cloudCoverage: constVal(0.49),
        cloudSigmaE: constVal(0.09),
      },
    },
    { // inside o - timelapse
      type: PATH.LINEAR_QUAT,
      duration: 4,
      from: [-2.33, 1.56, 8.8, -0.89 * Math.PI, 0.0 * Math.PI, 0.0 * Math.PI],
      to: [-2.33, 1.56, 8.8, -0.89 * Math.PI, 0.0 * Math.PI, 0.0 * Math.PI],
      fixedHeight: true,
      rawT: true,
      fadeIn: true,
      fadeOut: true,
      timeOverrides: {
        timeOfDay: { from: 0.5, to: 19 },
        dofBlurFar: { from: 1, to: 10001 },
        dofFocusFar: { from: 0.1, to: 10000 },
      },
    },
    { // over the text at night
      type: PATH.LINEAR_QUAT,
      duration: 10,
      from: [4.74, 3.5, 11.53, -0.4 * Math.PI, -0.5 * Math.PI, 0.0],
      to: [-26.65, 3.5, 1.23, -0.4 * Math.PI, -0.5 * Math.PI, 0.0],
      fixedHeight: true,
      rawT: true,
      fadeIn: true,
      fadeOut: true,
      timeOverrides: {
        timeOfDay: constVal(21.5),
        rain: constVal(0.0),
        depthOfField: constVal(0),
      },
    },
    { // timelapse move over the field
      type: PATH.LINEAR_QUAT,
      duration: 8,
      from: [30, 1.0, 20, -2.0 * 2.73, -0.02, 0.0],
      to: [-20, 1.0, 20, -1.73, -0.02, 0.0],
      fixedHeight: true,
      rawT: false,
      fadeIn: true,
      fadeOut: true,
      timeOverrides: {
        timeOfDay: { from: 5.9, to: 20.5 },
        cloudCoverage: { from: 0.45, to: 0.5 },
        cloudSteps: constVal(S.isMobile ? 12 : 16),
        cloudShadowSteps: constVal(S.isMobile ? 1 : 2),
        cloudDensity: { from: 0.4, to: 0.2 },
        rain: constVal(0.0),
        depthOfField: constVal(S.isMobile ? 0.0 : 1.1),
        cloudBase: constVal(70.0),
        cloudTop: { from: 100, to: 90.0 },
      },
    },
    /*{ // end of field time lapse
      type: PATH.STATIC,
      duration: 1.0,
      at: [-20, 1.0, 20],
      fixedHeight: true,
      fadeOut: true,
      //rawT: true,
      timeOfDay: { from: 20.5, to: 23.5 },
    },*/
    { // looking up from grass to the sun
      type: PATH.STATIC,
      duration: 5,
      at: [-20, 0.001, 20],
      lookAt: [-1, 15, -1],
      rawT: true,
      timeOverrides: {
        lensFlareIntensity: constVal(2.0),
        depthOfField: constVal(S.isMobile ? 0 : 0.2),
        grassWidthFactor: constVal(0.25),
        grassHeightFactor: constVal(1.0),
        godRaySteps: constVal(S.isMobile ? 32 : 64),
        cloudSteps: constVal(S.isMobile ? 8 : 12),
        cloudShadowSteps: constVal(S.isMobile ? 2 : 3),
        cloudBase: null,
        cloudTop: null,
        fogSteps: constVal(S.isMobile ? 4 : 8),
        rain: constVal(0.0),
        cloudCoverage: constVal(1.0),
        timeOfDay: constVal(12.0),
      },
    },
    { // move in front of text
      type: PATH.LINEAR_LOOKAT,
      duration: 3,
      from: [-20, 0.001, 20],
      to: [0, 0.4, 0],
      startLookAt: [-1, 15, -1],
      endLookAt: [-10, 1, 10],
      timeOverrides: {
        lensFlareIntensity: { from: 2.0, to: 1.0 },
        depthOfField: S.isMobile ? constVal(0.0) : { from: 0.1, to: 1.34 },
        grassHeightFactor: { from: 1.0, to: 0.25 },
        grassWidthFactor: constVal(0.25),
        timeOfDay: { from: 12.0, to: 16.0 },
        cloudCoverage: { from: 1.0, to: 0.59 },
      },
    },
    { // look at text
      type: PATH.STATIC,
      duration: 0.5,
      at: [0, 0.4, 0],
      lookAt: [-10, 1, 10],
    },
    { // make it rain
      type: PATH.LINEAR_POS,
      duration: 0.5,
      from: [0, 0.4, 0],
      to: [0, 0.4, 0],
      lookAt: [-10, 1, 10],
      timeOverrides: {
        rain: { from: 0.0, to: 1.0 },
      },
    },
    { // watch grass grow
      type: PATH.STATIC,
      duration: 4,
      at: [0, 0.4, 0],
      lookAt: [-10, 1, 10],
      timeOverrides: {
        grassWidthFactor: { from: 0.25, to: 1.0 },
        grassHeightFactor: { from: 0.25, to: 1.0 },
      },
    }, // pause
    { type: PATH.STATIC, duration: 2, at: [0, 0.4, 0], lookAt: [-10, 1, 10] },
    { // cinematic shot
      type: PATH.LINEAR_QUAT,
      duration: 6,
      from: [0.81, 0.94, 7.93, -0.55 * Math.PI, 0.0 * Math.PI, 0.0 * Math.PI],
      to: [0.81, 0.94, 7.93, -0.55 * Math.PI, 0.0 * Math.PI, 0.0 * Math.PI],
      fixedHeight: true,
      fadeIn: true,
      fadeOut: true,
      timeOverrides: {
        lensFlareIntensity: null,
        rain: constVal(0.0),
        timeOfDay: constVal(20.6),
        turbidity: constVal(2.28),
        overcast: constVal(0.21),
        cloudBase: constVal(44),
        cloudTop: constVal(79),
        cloudCoverage: constVal(0.45),
        cloudDensity: constVal(0.03),
        cloudSteps: constVal(6),
        godRayIntensity: constVal(3.3),
        godRayDecay: constVal(0.84),
        godRaySteps: constVal(64),
        dofFocusNear: constVal(2.5),
        dofBlurNear: constVal(0.5),
        dofFocusFar: constVal(500),
        dofBlurFar: constVal(600),
      },
    },
    { // fly through th e text
      type: PATH.LINEAR_QUAT,
      duration: 8.0,
      from: [tx - 4.5, 1.0, 20, 0.0 * Math.PI, 0, -0.25],
      to: [tx - 32.5, 1.5, -20, -1.5 * Math.PI, 0, 0.125],
      fadeIn: true,
      fadeOut: true,
      fixedHeight: true,
      timeOverrides: {
        turbidity: null,
        overcast: null,
        cloudBase: null,
        cloudTop: null,
        cloudDensity: null,
        cloudSteps: null,
        godRayIntensity: null,
        godRayDecay: null,
        godRaySteps: null,

        dofFocusNear: constVal(1.0),
        dofBlurNear: constVal(0.5),
        dofFocusFar: { from: 2.5, to: 50 },
        dofBlurFar: { from: 4.0, to: 101 },
        depthOfField: { from: 1.0, to: 0.5 },
        timeOfDay: constVal(6.5),
        cloudCoverage: constVal(0.59),
        rain: constVal(0.0),
      },
    },
    { // sunrise
      type: PATH.LINEAR_QUAT,
      duration: 10.0,
      from: [0.14, 0.84, 9.36, -0.61 * Math.PI, 0.21 * Math.PI, -2.0 * Math.PI],
      to: [-20.74, 1.0, -0.05, -1.23 * Math.PI, 0.05 * Math.PI, -0.0 * Math.PI],
      fadeIn: true,
      timeOverrides: {
        overcast: constVal(0.21),
        dofBlurFar: constVal(10001),
        dofFocusFar: constVal(10000),
        depthOfField: constVal(S.isMobile ? 0.0 : 1.34),
        cloudBase: { from: 70, to: 60 },
        cloudTop: { from: 80, to: 100 },
        cloudCoverage: { from: 0.59, to: 0.41 },
        godRayIntensity: constVal(3.9),
        godRayDecay: { from: 0.99, to: 0.75 },
        timeOfDay: constVal(3)
      },
    },
    { // watch the sun rise
      type: PATH.STATIC,
      duration: 4.0,
      at: [tx - 20.74, 1.0, -0.05],
      timeOverrides: {
        timeOfDay: { from: 3, to: 8 },
      },
    },
    { // watch the sun rise - pause
      type: PATH.STATIC,
      fadeOut: true,
      duration: 1.0,
      at: [tx - 20.74, 1.0, -0.05],
    },
    {
      type: PATH.ORBIT,
      duration: 10.0,
      center: [tx - 10, ty, tz],
      distance: 8,
      fadeIn: true,
      rawT: true,
      fixedHeight: true,
      startElevation: Math.PI * 0.02,
      endElevation: Math.PI * 0.06,
      startAngle: -Math.PI * 0.125,
      endAngle: Math.PI * 0.4,
      fixedHeight: true,
      timeOverrides: {
        overcast: null,
        fogSteps: constVal(S.isMobile ? 12 : 16),
        godRayIntensity: constVal(0.0),
        godRayDecay: constVal(0.0),
        timeOfDay: constVal(23),
        cloudCoverage: constVal(1.0),
        fogDensity: { from: 0.0, to: 0.24 },
        fogHeightFalloff: { from: 0.5, to: 2.5 },
        fogIntensity: { from: 0.3, to: 0.9 },
        fogQuality: constVal(1.0),
      },
    },
    {
      type: PATH.ORBIT,
      duration: 10.0,
      center: [tx - 10, ty, tz],
      distance: 12,
      startElevation: Math.PI * 0.03,
      endElevation: Math.PI * 0.02,
      startAngle: Math.PI * 0.25,
      endAngle: -Math.PI * 0.125,
      rawT: true,
      fixedHeight: true,
      fadeOut: true,
      timeOverrides: {
        timeOfDay: constVal(3),
        fogDensity: constVal(0.6),
        fogIntensity: constVal(1.5),
        fogHeightFalloff: constVal(0.5),
        windStrength: constVal(0.5),
        fogSteps: constVal(S.isMobile ? 16 : 32),
      },
    },
    {
      type: PATH.STATIC,
      duration: 3,
      at: [0, 0.45, 0],
      lookAt: [x, y, z],
      fadeOut: true,
      timeOverrides: {
        fogSteps: constVal(S.isMobile ? 12 : 16),
        fogHeightFalloff: constVal(0.3),
        fogIntensity: constVal(0.2),
        depthOfField: constVal(2.0),
        dewAmount: constVal(1.0),
        windStrength: null,
        time: { from: 3, to: 5 },
      },
    },
    {
      type: PATH.LINEAR_LOOKAT,
      duration: 4,
      from: [0, 0.4, 0],
      to: S.initPos,
      fadeIn: true,
      startLookAt: [x, y, z],
      endLookAt: S.initLookAt,
      timeOverrides: "reset",
    },
  ]
}
